using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Prizm.Domain.Entity
{
    /// <summary>
    /// All items in this list should correspond to appropriate types of Entity Field Name.
    /// Do not reorder the item number and Field Name.
    /// </summary>
    public enum FieldNames
    {

        Undefined = 0,
        Name = 1,
        ConnectorsCount = 2,
        IsNative = 3,
        Project = 4,
        Diameter = 5,
        WallThickness = 6,
        Joint = 7,
        Component = 8,
        Number = 9,
        NumberKP = 10,
        DistanceFromKP = 11,
        LoweringDate = 12,
        Status = 13,
        GpsLatitude = 14,
        GpsLongitude = 15,
        GpsHeight = 16, 
        FirstElement = 17, 
        SecondElement = 18,
        ToExport = 19,
        IsCompleted = 20,
        Date = 21,
        Operation = 22,
        FileName = 23,
        Description = 24,
        UploadDate = 25, 
        Item = 26,
        NewName = 27,
        Fixed = 28,
        ResultType = 29,
        Type = 30,
        Pipe = 31,
        SteelGrade = 32,
        PlateManufacturer = 33,
        Thickness = 34, 
        Heat = 35,
        Certificate = 36,
        Destination = 37,
        IsShipped = 38,
        ReleaseNote = 39,
        Shipped = 40,
        Parameter = 41,
        BaseValue = 42,
        JointValue = 43,
        Length = 44,
        IsAvailableToJoint = 45,
        ConstructionStatus = 46,
        InspectionStatus = 47,
        FirstName = 48,
        LastName = 49,
        MiddleName = 50,
        Login = 51,
        PasswordHash = 52,
        PasswordExpires = 53,
        Undeletable = 54,
        Inspector = 55,
        IsRequired = 56,
        TestHasAccepted = 57,
        TestHasToRepair = 58,
        TestHasToWithdraw = 59,
        TestResultRequired = 60,
        Category = 61,
        Code = 62,
        MinExpected = 63,
        MaxExpected = 64,
        StringExpected = 65,
        BoolExpected = 66,
        pipeType = 67,
        Frequency = 68,
        ControlType = 69,
        Quantaty = 70,
        Measure = 71,
        Title = 72,
        Client = 73,
        MillName = 74,
        DocumentSizeLimit = 75,
        WorkstationType = 76,
        MillPipeNumberMask = 77,
        MillPipeNumberMaskRegexp = 78,
        Stamp = 79,
        Grade = 80,
        Value = 81,
        Id = 82,
        IsActive = 83,
        Order = 84,
        ExpirationDate = 85,
        Part = 86,
        PipeNumber = 87,
        Plate = 88,
        Mill = 89,
        Weight = 90,
        ProductionDate = 91,
        PurchaseOrder = 92,
        IsCutOnSpool = 93,
        WeldSubStatus = 94,
        ExternalCoatSubStatus = 95,
        InternalCoatSubStatus = 96,
        SeamType = 97,
        Railcar = 98,
        PartTypeDescription = 99,

    }
}
