//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrizmMain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrizmMain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка!.
        /// </summary>
        internal static string AlertFailureHeader {
            get {
                return ResourceManager.GetString("AlertFailureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание.
        /// </summary>
        internal static string AlertInfoHeader {
            get {
                return ResourceManager.GetString("AlertInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение успешно.
        /// </summary>
        internal static string AlertSaveHeader {
            get {
                return ResourceManager.GetString("AlertSaveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные вагона сохранены.
        /// </summary>
        internal static string AlertSaveRailcar {
            get {
                return ResourceManager.GetString("AlertSaveRailcar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вагон успешно отгружен.
        /// </summary>
        internal static string AlertShipRailcar {
            get {
                return ResourceManager.GetString("AlertShipRailcar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отгрузка вагона отменена. Дата отгрузки аннулированна. Трубы перемещены на склад..
        /// </summary>
        internal static string AlertUnsipRailcar {
            get {
                return ResourceManager.GetString("AlertUnsipRailcar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внешнее.
        /// </summary>
        internal static string COAT_EXTERNAL {
            get {
                return ResourceManager.GetString("COAT_EXTERNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутреннее.
        /// </summary>
        internal static string COAT_INTERNAL {
            get {
                return ResourceManager.GetString("COAT_INTERNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string DLG_ERROR_HEADER {
            get {
                return ResourceManager.GetString("DLG_ERROR_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить редактирование трубы?.
        /// </summary>
        internal static string DLG_PIPE_CREATION {
            get {
                return ResourceManager.GetString("DLG_PIPE_CREATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание трубы.
        /// </summary>
        internal static string DLG_PIPE_CREATION_HEDER {
            get {
                return ResourceManager.GetString("DLG_PIPE_CREATION_HEDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение данных приведет к деактивации трубы. Деактивировать трубу?.
        /// </summary>
        internal static string DLG_PIPE_DEACTIVATION {
            get {
                return ResourceManager.GetString("DLG_PIPE_DEACTIVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деактивация трубы.
        /// </summary>
        internal static string DLG_PIPE_DEACTIVATION_HEDER {
            get {
                return ResourceManager.GetString("DLG_PIPE_DEACTIVATION_HEDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите номер вагона.
        /// </summary>
        internal static string DLG_RAILCAR_NUMBER_EMPTY {
            get {
                return ResourceManager.GetString("DLG_RAILCAR_NUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данная труба находится в вагоне #.
        /// </summary>
        internal static string DLG_RAILCAR_PIPE_IN_OTHER_CAR_ERROR {
            get {
                return ResourceManager.GetString("DLG_RAILCAR_PIPE_IN_OTHER_CAR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все трубы в в вагоне должны быть одного типоразмера.
        /// </summary>
        internal static string DLG_RAILCAR_TYPESIZE_ERROR {
            get {
                return ResourceManager.GetString("DLG_RAILCAR_TYPESIZE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сначала расформируйте вагон..
        /// </summary>
        internal static string DLG_RAILCAR_UNSHIP_FIRST {
            get {
                return ResourceManager.GetString("DLG_RAILCAR_UNSHIP_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка вагона без труб невозможна.
        /// </summary>
        internal static string DLG_SHIP_RAILCAR_VS_PIPES {
            get {
                return ResourceManager.GetString("DLG_SHIP_RAILCAR_VS_PIPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вагон не отгружен.
        /// </summary>
        internal static string DLG_UNSHIP_UNSHIPPED_RAILCAR {
            get {
                return ResourceManager.GetString("DLG_UNSHIP_UNSHIPPED_RAILCAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не пройден.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время работы программы произошла ошибка. Причина: .
        /// </summary>
        internal static string IDS_ERROR {
            get {
                return ResourceManager.GetString("IDS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя одновременно открыть больше документов..
        /// </summary>
        internal static string IDS_NO_MORE_DOCUMENTS {
            get {
                return ResourceManager.GetString("IDS_NO_MORE_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить запись?.
        /// </summary>
        internal static string IDS_QUESTION_DELETE_SELECTED {
            get {
                return ResourceManager.GetString("IDS_QUESTION_DELETE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить изменения?.
        /// </summary>
        internal static string IDS_QUESTION_SAVE {
            get {
                return ResourceManager.GetString("IDS_QUESTION_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательный.
        /// </summary>
        internal static string InspectionControlType_Hold {
            get {
                return ResourceManager.GetString("InspectionControlType_Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Визуальный.
        /// </summary>
        internal static string InspectionControlType_Monitor {
            get {
                return ResourceManager.GetString("InspectionControlType_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По документации.
        /// </summary>
        internal static string InspectionControlType_Review {
            get {
                return ResourceManager.GetString("InspectionControlType_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присутствие.
        /// </summary>
        internal static string InspectionControlType_Witness {
            get {
                return ResourceManager.GetString("InspectionControlType_Witness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логический.
        /// </summary>
        internal static string InspectionResultType_Boolean {
            get {
                return ResourceManager.GetString("InspectionResultType_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диапазон.
        /// </summary>
        internal static string InspectionResultType_Diapason {
            get {
                return ResourceManager.GetString("InspectionResultType_Diapason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка.
        /// </summary>
        internal static string InspectionResultType_String {
            get {
                return ResourceManager.GetString("InspectionResultType_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пройден.
        /// </summary>
        internal static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIZM.
        /// </summary>
        internal static string PRIZM {
            get {
                return ResourceManager.GetString("PRIZM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производится.
        /// </summary>
        internal static string Produced {
            get {
                return ResourceManager.GetString("Produced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидается.
        /// </summary>
        internal static string Scheduled {
            get {
                return ResourceManager.GetString("Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отгружена.
        /// </summary>
        internal static string Shipped {
            get {
                return ResourceManager.GetString("Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На складе.
        /// </summary>
        internal static string Stocked {
            get {
                return ResourceManager.GetString("Stocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение обязательно.
        /// </summary>
        internal static string VALUE_REQUIRED {
            get {
                return ResourceManager.GetString("VALUE_REQUIRED", resourceCulture);
            }
        }
    }
}
